# Generated by Django 4.2.6 on 2023-11-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0003_alter_roleassoc_role_alter_roleassoc_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteAssoc',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='role',
            name='created',
        ),
        migrations.RemoveField(
            model_name='role',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='RoleAssoc',
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.ManyToManyField(related_name='contacts', to='fcapi.role'),
        ),
    ]
