# Generated by Django 4.2.6 on 2023-11-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0004_delete_noteassoc_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
