# Generated by Django 4.2.6 on 2023-11-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0007_alter_role_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contacts',
            field=models.ManyToManyField(related_name='jobs', to='fcapi.contact'),
        ),
    ]
