# Generated by Django 4.2.7 on 2023-11-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0010_alter_contact_options_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('U', 'Unknown'), ('O', 'Office'), ('H', 'Hybrid'), ('R', 'Remote')], default='U', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('U', 'Unknown'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')], default='U', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('EI', 'Expressed Interest'), ('A', 'Applied'), ('I', 'Interviewing'), ('O', 'Pending Offer'), ('R', 'Rejection Received'), ('W', 'Withdrawn')], default='U', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='travel',
            field=models.CharField(choices=[('U', 'Unknown'), ('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='U', max_length=50),
        ),
    ]
