# Generated by Django 4.2.7 on 2023-11-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0014_alter_job_location_alter_job_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='compensation',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='Unknown', max_length=50),
        ),
    ]
