# Generated by Django 4.2.7 on 2023-11-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0015_job_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='compensation',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Office'), ('2', 'Hybrid'), ('3', 'Remote')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Critical')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('0', 'Expressed Interest'), ('1', 'Applied'), ('2', 'Interviewing'), ('3', 'Pending Offer'), ('4', 'Rejection Received'), ('5', 'Withdrawn')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='travel',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'None'), ('2', 'Low'), ('3', 'Medium'), ('4', 'High')], default='0', max_length=50),
        ),
    ]
