"""
URL configuration for fc project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
#from django.urls import path
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ContactViewSet,
    NoteViewSet,
    RoleViewSet,
    CompanyViewSet,
    JobViewSet,
    LogViewSet,
)

# Create a router for the viewsets
router = DefaultRouter()

# Register the viewsets with the router
router.register(r'contacts', ContactViewSet)
router.register(r'notes', NoteViewSet)
router.register(r'roles', RoleViewSet)
router.register(r'companies', CompanyViewSet)
router.register(r'jobs', JobViewSet)
router.register(r'logs', LogViewSet)

urlpatterns = [
    # Include the API views generated by the router
    path('', include(router.urls)),

]
